// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Societate_de_Valori.Data;

#nullable disable

namespace Societate_de_Valori.Migrations
{
    [DbContext(typeof(Societate_de_ValoriContext))]
    [Migration("20220122132246_Tip")]
    partial class Tip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Societate_de_Valori.Models.Firma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("NumarAngajati")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeActiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Investitor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubiectDeDreptID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SubiectDeDreptID");

                    b.ToTable("Investitor");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Platforma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Platforma");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.SubiectDeDrept", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SubiectDeDrept");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.TipTranzactie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TipTranzactie");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Tranzactie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("InvestitorID")
                        .HasColumnType("int");

                    b.Property<int>("PlatformaID")
                        .HasColumnType("int");

                    b.Property<int>("Suma")
                        .HasColumnType("int");

                    b.Property<int>("TipTranzactieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FirmaID");

                    b.HasIndex("InvestitorID");

                    b.HasIndex("PlatformaID");

                    b.HasIndex("TipTranzactieID");

                    b.ToTable("Tranzactie");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Valuta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Valuta");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Investitor", b =>
                {
                    b.HasOne("Societate_de_Valori.Models.SubiectDeDrept", "SubiectDeDrept")
                        .WithMany()
                        .HasForeignKey("SubiectDeDreptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubiectDeDrept");
                });

            modelBuilder.Entity("Societate_de_Valori.Models.Tranzactie", b =>
                {
                    b.HasOne("Societate_de_Valori.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Societate_de_Valori.Models.Investitor", "Investitor")
                        .WithMany()
                        .HasForeignKey("InvestitorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Societate_de_Valori.Models.Platforma", "Platforma")
                        .WithMany()
                        .HasForeignKey("PlatformaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Societate_de_Valori.Models.TipTranzactie", "TipTranzactie")
                        .WithMany()
                        .HasForeignKey("TipTranzactieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Investitor");

                    b.Navigation("Platforma");

                    b.Navigation("TipTranzactie");
                });
#pragma warning restore 612, 618
        }
    }
}
